name: Ubuntu Build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [latest, branch@master, branch@dev]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@master
        with:
          xmake-version: ${{ matrix.version }}
      - name: Before Install
        run: |
          sudo apt-get install g++-10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 90
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"
      - name: Run tests
        run: |
          xmake --version
          xmake f -m release -y
          xmake
          xmake run test
